/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finaltrabajo.vistas;

import finaltrabajo.BaseDatosAcademia;
import finaltrabajo.Serializador;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author yuripastorovic
 */
public class AjustesLocal extends javax.swing.JFrame {

    /**
     * Creates new form AjustesLocal
     */
    private BaseDatosAcademia bd = new BaseDatosAcademia();
    private Serializador sc = new Serializador();

    public AjustesLocal() {
        initComponents();
    }

    public JPanel getFondo() {
        JPanel fondo = PanelFondo;
        return fondo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        CARGAR_LOCAL = new javax.swing.JPanel();
        LabelButtonModificar2 = new javax.swing.JLabel();
        COPIA_LOCAL = new javax.swing.JPanel();
        LabelButtonModificar1 = new javax.swing.JLabel();
        GENERAR_INFORMES = new javax.swing.JPanel();
        LabelButtonModificar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo.setBackground(new java.awt.Color(221, 214, 204));

        jPanel2.setBackground(new java.awt.Color(184, 67, 87));

        jPanel3.setBackground(new java.awt.Color(189, 146, 64));

        CARGAR_LOCAL.setBackground(new java.awt.Color(25, 34, 43));
        CARGAR_LOCAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CARGAR_LOCAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CARGAR_LOCALModificar_clicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CARGAR_LOCALMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CARGAR_LOCALMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CARGAR_LOCALMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CARGAR_LOCALMouseReleased(evt);
            }
        });

        LabelButtonModificar2.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        LabelButtonModificar2.setForeground(new java.awt.Color(221, 214, 204));
        LabelButtonModificar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelButtonModificar2.setText("CARGAR LOCAL");

        javax.swing.GroupLayout CARGAR_LOCALLayout = new javax.swing.GroupLayout(CARGAR_LOCAL);
        CARGAR_LOCAL.setLayout(CARGAR_LOCALLayout);
        CARGAR_LOCALLayout.setHorizontalGroup(
            CARGAR_LOCALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CARGAR_LOCALLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelButtonModificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CARGAR_LOCALLayout.setVerticalGroup(
            CARGAR_LOCALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelButtonModificar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        COPIA_LOCAL.setBackground(new java.awt.Color(25, 34, 43));
        COPIA_LOCAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        COPIA_LOCAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                COPIA_LOCALModificar_clicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                COPIA_LOCALMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                COPIA_LOCALMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                COPIA_LOCALMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                COPIA_LOCALMouseReleased(evt);
            }
        });

        LabelButtonModificar1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        LabelButtonModificar1.setForeground(new java.awt.Color(221, 214, 204));
        LabelButtonModificar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelButtonModificar1.setText("GEN COPIA LOCAL");

        javax.swing.GroupLayout COPIA_LOCALLayout = new javax.swing.GroupLayout(COPIA_LOCAL);
        COPIA_LOCAL.setLayout(COPIA_LOCALLayout);
        COPIA_LOCALLayout.setHorizontalGroup(
            COPIA_LOCALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, COPIA_LOCALLayout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(LabelButtonModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        COPIA_LOCALLayout.setVerticalGroup(
            COPIA_LOCALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelButtonModificar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        GENERAR_INFORMES.setBackground(new java.awt.Color(25, 34, 43));
        GENERAR_INFORMES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GENERAR_INFORMES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GENERAR_INFORMESModificar_press(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GENERAR_INFORMESMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GENERAR_INFORMESMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GENERAR_INFORMESMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                GENERAR_INFORMESMouseReleased(evt);
            }
        });

        LabelButtonModificar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        LabelButtonModificar.setForeground(new java.awt.Color(221, 214, 204));
        LabelButtonModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelButtonModificar.setText("GENERAR INFORMES");

        javax.swing.GroupLayout GENERAR_INFORMESLayout = new javax.swing.GroupLayout(GENERAR_INFORMES);
        GENERAR_INFORMES.setLayout(GENERAR_INFORMESLayout);
        GENERAR_INFORMESLayout.setHorizontalGroup(
            GENERAR_INFORMESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GENERAR_INFORMESLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(LabelButtonModificar))
        );
        GENERAR_INFORMESLayout.setVerticalGroup(
            GENERAR_INFORMESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GENERAR_INFORMES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CARGAR_LOCAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(COPIA_LOCAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(CARGAR_LOCAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GENERAR_INFORMES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(COPIA_LOCAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addContainerGap(542, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COPIA_LOCALModificar_clicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COPIA_LOCALModificar_clicked
        sc.copiaLocal();

        COPIA_LOCAL.setBackground(new Color(184, 67, 87));
        COPIA_LOCAL.setForeground(new Color(189, 146, 64));
    }//GEN-LAST:event_COPIA_LOCALModificar_clicked

    private void COPIA_LOCALMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COPIA_LOCALMouseEntered
        COPIA_LOCAL.setBackground(new Color(184, 67, 87));
        LabelButtonModificar1.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_COPIA_LOCALMouseEntered

    private void COPIA_LOCALMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COPIA_LOCALMouseExited
        COPIA_LOCAL.setBackground(new Color(25, 34, 43));
        LabelButtonModificar1.setForeground(new Color(221, 214, 204));
    }//GEN-LAST:event_COPIA_LOCALMouseExited

    private void COPIA_LOCALMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COPIA_LOCALMousePressed
        COPIA_LOCAL.setBackground(new Color(221, 214, 204));
        LabelButtonModificar1.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_COPIA_LOCALMousePressed

    private void COPIA_LOCALMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COPIA_LOCALMouseReleased
        COPIA_LOCAL.setBackground(new Color(189, 146, 64));
        COPIA_LOCAL.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_COPIA_LOCALMouseReleased

    private void GENERAR_INFORMESModificar_press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GENERAR_INFORMESModificar_press
        bd.guardarEnFicheroTextoAlumnos("informeAlumnos.txt");
        bd.guardarEnFicheroTextoCursos("informeCursos.txt");
        bd.guardarEnFicheroTextoInscripciones("informeInscripciones.txt");
    }//GEN-LAST:event_GENERAR_INFORMESModificar_press

    private void GENERAR_INFORMESMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GENERAR_INFORMESMouseEntered
        GENERAR_INFORMES.setBackground(new Color(189, 146, 64));
        LabelButtonModificar.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_GENERAR_INFORMESMouseEntered

    private void GENERAR_INFORMESMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GENERAR_INFORMESMouseExited
        GENERAR_INFORMES.setBackground(new Color(25, 34, 43));
        LabelButtonModificar.setForeground(new Color(221, 214, 204));
    }//GEN-LAST:event_GENERAR_INFORMESMouseExited

    private void GENERAR_INFORMESMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GENERAR_INFORMESMousePressed
        GENERAR_INFORMES.setBackground(new Color(184, 67, 87));
        GENERAR_INFORMES.setForeground(new Color(189, 146, 64));
    }//GEN-LAST:event_GENERAR_INFORMESMousePressed

    private void GENERAR_INFORMESMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GENERAR_INFORMESMouseReleased
        GENERAR_INFORMES.setBackground(new Color(189, 146, 64));
        GENERAR_INFORMES.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_GENERAR_INFORMESMouseReleased

    private void CARGAR_LOCALModificar_clicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARGAR_LOCALModificar_clicked
        sc.uploadLocal();
    }//GEN-LAST:event_CARGAR_LOCALModificar_clicked

    private void CARGAR_LOCALMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARGAR_LOCALMouseEntered
        CARGAR_LOCAL.setBackground(new Color(189, 146, 64));
        LabelButtonModificar2.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_CARGAR_LOCALMouseEntered

    private void CARGAR_LOCALMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARGAR_LOCALMouseExited
       CARGAR_LOCAL.setBackground(new Color(25, 34, 43));
        LabelButtonModificar2.setForeground(new Color(221, 214, 204));
    }//GEN-LAST:event_CARGAR_LOCALMouseExited

    private void CARGAR_LOCALMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARGAR_LOCALMousePressed
       CARGAR_LOCAL.setBackground(new Color(184, 67, 87));
        LabelButtonModificar2.setForeground(new Color(189, 146, 64));
    }//GEN-LAST:event_CARGAR_LOCALMousePressed

    private void CARGAR_LOCALMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARGAR_LOCALMouseReleased
        CARGAR_LOCAL.setBackground(new Color(189, 146, 64));
        LabelButtonModificar2.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_CARGAR_LOCALMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjustesLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjustesLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjustesLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjustesLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjustesLocal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CARGAR_LOCAL;
    private javax.swing.JPanel COPIA_LOCAL;
    private javax.swing.JPanel GENERAR_INFORMES;
    private javax.swing.JLabel LabelButtonModificar;
    private javax.swing.JLabel LabelButtonModificar1;
    private javax.swing.JLabel LabelButtonModificar2;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
