/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finaltrabajo.vistas;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author yuripastorovic
 */
public class Inscripciones extends javax.swing.JFrame {

    /**
     * Creates new form Inscripciones
     */
    public Inscripciones() {
        initComponents();
    }

    /**
     * Permite devolver el panel de fondo que contiene todos los componenetes
     * del JFrame
     *
     * @return fondo
     */
    public JPanel getFondo() {
        JPanel fondo = PanelFondo;
        return fondo;
    }

    /**
     * Método que permite mostrar un JFrame en un JPanel
     *
     * @param panel
     */
    private void showPanel(JPanel panel) {
        panel.setSize(this.contenedor.getWidth(), this.contenedor.getHeight());
        panel.setLocation(0, 0);
        this.contenedor.removeAll();
        this.contenedor.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        this.contenedor.revalidate();
        this.contenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        PanelFaldon = new javax.swing.JPanel();
        ALTA_BAJA = new javax.swing.JPanel();
        LabelButtonModificar4 = new javax.swing.JLabel();
        CALIFICAR = new javax.swing.JPanel();
        LabelButtonModificar3 = new javax.swing.JLabel();
        MOSTRAR = new javax.swing.JPanel();
        LabelButtonModificar = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        caja = new javax.swing.JPanel();
        texto = new javax.swing.JLabel();
        curso_img = new javax.swing.JLabel();
        insc_txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(757, 322));

        PanelFondo.setBackground(new java.awt.Color(184, 67, 87));

        PanelFaldon.setBackground(new java.awt.Color(25, 34, 43));

        ALTA_BAJA.setBackground(new java.awt.Color(25, 34, 43));
        ALTA_BAJA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ALTA_BAJA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ALTA_BAJABuscar_alum(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ALTA_BAJAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ALTA_BAJAMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ALTA_BAJAMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ALTA_BAJAMouseReleased(evt);
            }
        });

        LabelButtonModificar4.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        LabelButtonModificar4.setForeground(new java.awt.Color(221, 214, 204));
        LabelButtonModificar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelButtonModificar4.setText("ALTA / BAJA INSCRIPCION");

        javax.swing.GroupLayout ALTA_BAJALayout = new javax.swing.GroupLayout(ALTA_BAJA);
        ALTA_BAJA.setLayout(ALTA_BAJALayout);
        ALTA_BAJALayout.setHorizontalGroup(
            ALTA_BAJALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelButtonModificar4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ALTA_BAJALayout.setVerticalGroup(
            ALTA_BAJALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelButtonModificar4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        CALIFICAR.setBackground(new java.awt.Color(25, 34, 43));
        CALIFICAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CALIFICAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CALIFICARModi_alum(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CALIFICARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CALIFICARMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CALIFICARMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CALIFICARMouseReleased(evt);
            }
        });

        LabelButtonModificar3.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        LabelButtonModificar3.setForeground(new java.awt.Color(221, 214, 204));
        LabelButtonModificar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelButtonModificar3.setText("CALIFICAR");

        javax.swing.GroupLayout CALIFICARLayout = new javax.swing.GroupLayout(CALIFICAR);
        CALIFICAR.setLayout(CALIFICARLayout);
        CALIFICARLayout.setHorizontalGroup(
            CALIFICARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelButtonModificar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );
        CALIFICARLayout.setVerticalGroup(
            CALIFICARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelButtonModificar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        MOSTRAR.setBackground(new java.awt.Color(25, 34, 43));
        MOSTRAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MOSTRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MOSTRARBaja_alum(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MOSTRARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MOSTRARMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MOSTRARMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MOSTRARMouseReleased(evt);
            }
        });

        LabelButtonModificar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        LabelButtonModificar.setForeground(new java.awt.Color(221, 214, 204));
        LabelButtonModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelButtonModificar.setText("MOSTRAR INSCRIPCIONES");

        javax.swing.GroupLayout MOSTRARLayout = new javax.swing.GroupLayout(MOSTRAR);
        MOSTRAR.setLayout(MOSTRARLayout);
        MOSTRARLayout.setHorizontalGroup(
            MOSTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelButtonModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MOSTRARLayout.setVerticalGroup(
            MOSTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelButtonModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelFaldonLayout = new javax.swing.GroupLayout(PanelFaldon);
        PanelFaldon.setLayout(PanelFaldonLayout);
        PanelFaldonLayout.setHorizontalGroup(
            PanelFaldonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFaldonLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(ALTA_BAJA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CALIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MOSTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFaldonLayout.setVerticalGroup(
            PanelFaldonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFaldonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelFaldonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ALTA_BAJA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CALIFICAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MOSTRAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        contenedor.setBackground(new java.awt.Color(221, 214, 204));
        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caja.setBackground(new java.awt.Color(221, 214, 204));
        caja.setOpaque(false);

        texto.setBackground(new java.awt.Color(221, 214, 204));
        texto.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        texto.setForeground(new java.awt.Color(221, 214, 204));

        javax.swing.GroupLayout cajaLayout = new javax.swing.GroupLayout(caja);
        caja.setLayout(cajaLayout);
        cajaLayout.setHorizontalGroup(
            cajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cajaLayout.setVerticalGroup(
            cajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        contenedor.add(caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 750, -1));

        curso_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finaltrabajo/vistas/icon/inscripcion.png"))); // NOI18N
        contenedor.add(curso_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 360, 330));

        insc_txt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finaltrabajo/vistas/icon/inscrip_txt.png"))); // NOI18N
        contenedor.add(insc_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 260));

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFaldon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(PanelFaldon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Boton que te dirige a la seccion Alta inscripnciones
     *
     * @param evt
     */
    private void ALTA_BAJABuscar_alum(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALTA_BAJABuscar_alum
        InscripcionesAddDel bbb = new InscripcionesAddDel();
        showPanel(bbb.getFondo());
    }//GEN-LAST:event_ALTA_BAJABuscar_alum
    /**
     * Permite hacer cambiar el color del boton por interaccion del raton asi
     * como mostrar una descripcion del boton
     *
     * @param evt
     */
    private void ALTA_BAJAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALTA_BAJAMouseEntered
        // TODO add your handling code here:
        ALTA_BAJA.setBackground(new Color(189, 146, 64));
        LabelButtonModificar4.setForeground(new Color(25, 34, 43));
        caja.setBackground(new Color(25, 34, 43));
        texto.setForeground(new Color(221, 214, 204));
        texto.setText("PERMITE MATRICULAR O DESMATRICULAR UN ALUMNO EN ACTIVO");
        caja.setOpaque(true);
    }//GEN-LAST:event_ALTA_BAJAMouseEntered
    /**
     * Permite hacer cambiar el color del boton por interaccion del raton
     *
     * @param evt
     */
    private void ALTA_BAJAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALTA_BAJAMouseExited
        ALTA_BAJA.setBackground(new Color(25, 34, 43));
        LabelButtonModificar4.setForeground(new Color(221, 214, 204));
        caja.setBackground(new Color(221, 214, 204));
        texto.setText("");
        caja.setOpaque(false);
    }//GEN-LAST:event_ALTA_BAJAMouseExited
    /**
     * Permite hacer cambiar el color del boton por interaccion del raton
     *
     * @param evt
     */
    private void ALTA_BAJAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALTA_BAJAMousePressed
        ALTA_BAJA.setBackground(new Color(184, 67, 87));
        LabelButtonModificar4.setForeground(new Color(189, 146, 64));
    }//GEN-LAST:event_ALTA_BAJAMousePressed
    /**
     * Permite hacer cambiar el color del boton por interaccion del raton
     *
     * @param evt
     */
    private void ALTA_BAJAMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALTA_BAJAMouseReleased
        ALTA_BAJA.setBackground(new Color(189, 146, 64));
        LabelButtonModificar4.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_ALTA_BAJAMouseReleased
    /**
     * Permite acceder a la seccion Calificar alumno
     *
     * @param evt
     */
    private void CALIFICARModi_alum(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CALIFICARModi_alum
        InscripcionesGestion bbb = new InscripcionesGestion();
        showPanel(bbb.getFondo());
    }//GEN-LAST:event_CALIFICARModi_alum
    /**
     * Permite hacer cambiar el color del boton por interaccion del raton asi
     * como mostrar una descripcion del boton
     *
     * @param evt
     */
    private void CALIFICARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CALIFICARMouseEntered
        CALIFICAR.setBackground(new Color(189, 146, 64));
        LabelButtonModificar3.setForeground(new Color(25, 34, 43));
        caja.setBackground(new Color(25, 34, 43));
        texto.setForeground(new Color(221, 214, 204));
        texto.setText("PERMITE CALIFICAR A UN ALUMNO EN ACTIVO EN UN CURSO AL QUE ESTE PERTENEZCA");
        caja.setOpaque(true);
    }//GEN-LAST:event_CALIFICARMouseEntered
    /**
     * Permite hacer cambiar el color del boton por interaccion del raton
     *
     * @param evt
     */
    private void CALIFICARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CALIFICARMouseExited
        CALIFICAR.setBackground(new Color(25, 34, 43));
        LabelButtonModificar3.setForeground(new Color(221, 214, 204));
        caja.setBackground(new Color(221, 214, 204));
        texto.setText("");
        caja.setOpaque(false);
    }//GEN-LAST:event_CALIFICARMouseExited
    /**
     * Permite hacer cambiar el color del boton por interaccion del raton
     *
     * @param evt
     */
    private void CALIFICARMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CALIFICARMousePressed
        CALIFICAR.setBackground(new Color(184, 67, 87));
        LabelButtonModificar3.setForeground(new Color(189, 146, 64));
    }//GEN-LAST:event_CALIFICARMousePressed
    /**
     * Permite hacer cambiar el color del boton por interaccion del raton
     *
     * @param evt
     */
    private void CALIFICARMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CALIFICARMouseReleased
        CALIFICAR.setBackground(new Color(189, 146, 64));
        LabelButtonModificar3.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_CALIFICARMouseReleased
    /**
     * Permite acceder a Mostrar Inscripciones
     *
     * @param evt
     */
    private void MOSTRARBaja_alum(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MOSTRARBaja_alum
        InscripcionesMostrar bbb = new InscripcionesMostrar();
        showPanel(bbb.getFondo());
    }//GEN-LAST:event_MOSTRARBaja_alum
    /**
     * Permite hacer cambiar el color del boton por interaccion del raton asi
     * como mostrar una descripcion del boton
     *
     * @param evt
     */
    private void MOSTRARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MOSTRARMouseEntered
        MOSTRAR.setBackground(new Color(189, 146, 64));
        LabelButtonModificar.setForeground(new Color(25, 34, 43));
        caja.setBackground(new Color(25, 34, 43));
        texto.setForeground(new Color(221, 214, 204));
        texto.setText("PERMITE MOSTRAR EL REGISTRO DE INSCRIPCIONES DE ALUMNOS EN ACTIVO Y ESGRESADOS");
        caja.setOpaque(true);
    }//GEN-LAST:event_MOSTRARMouseEntered
    /**
     * Permite hacer cambiar el color del boton por interaccion del raton
     *
     * @param evt
     */
    private void MOSTRARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MOSTRARMouseExited
        MOSTRAR.setBackground(new Color(25, 34, 43));
        LabelButtonModificar.setForeground(new Color(221, 214, 204));
        caja.setBackground(new Color(221, 214, 204));
        texto.setText("");
        caja.setOpaque(false);
    }//GEN-LAST:event_MOSTRARMouseExited
    /**
     * Permite hacer cambiar el color del boton por interaccion del raton
     *
     * @param evt
     */
    private void MOSTRARMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MOSTRARMousePressed
        MOSTRAR.setBackground(new Color(184, 67, 87));
        LabelButtonModificar.setForeground(new Color(189, 146, 64));
    }//GEN-LAST:event_MOSTRARMousePressed
    /**
     * Permite hacer cambiar el color del boton por interaccion del raton
     *
     * @param evt
     */
    private void MOSTRARMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MOSTRARMouseReleased
        MOSTRAR.setBackground(new Color(189, 146, 64));
        LabelButtonModificar.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_MOSTRARMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscripciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ALTA_BAJA;
    private javax.swing.JPanel CALIFICAR;
    private javax.swing.JLabel LabelButtonModificar;
    private javax.swing.JLabel LabelButtonModificar3;
    private javax.swing.JLabel LabelButtonModificar4;
    private javax.swing.JPanel MOSTRAR;
    private javax.swing.JPanel PanelFaldon;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel caja;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel curso_img;
    private javax.swing.JLabel insc_txt;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
