/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finaltrabajo.vistas;

import finaltrabajo.BaseDatosAcademia;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yuripastorovic
 */
public class InscripcionesMostrar extends javax.swing.JFrame {

    /**
     * Creates new form InscripcionesMostrar
     */
    private BaseDatosAcademia bd = new BaseDatosAcademia();
    private DefaultTableModel modelo = new DefaultTableModel();
    public InscripcionesMostrar() {
        initComponents();
        comboBox1();
        comboBox2();
        comboBox3();
        comboBox4();
        modelo.addColumn("ID");
        modelo.addColumn("ID_ALUMNO");
        modelo.addColumn("ID_CURSO");
        modelo.addColumn("FECHA_INICIO");
        modelo.addColumn("FECHA_FIN");
        modelo.addColumn("NOTA");
    }
public JPanel getFondo() {
        JPanel fondo = PanelFondo;
        return fondo;
    }
private void comboBox1() {
        String arrayString[] = bd.leerIdNombreApellidoAlumnosExistentesInscritos();
        ComboNombre.setModel(new javax.swing.DefaultComboBoxModel<>(arrayString));
    }
private void comboBox2() {
        String arrayString[] = bd.leerIdNombreApellidoAlumnosNoExistentesInscritos();
        ComboNombre1.setModel(new javax.swing.DefaultComboBoxModel<>(arrayString));
    }
private void comboBox3() {
        String arrayString[] = bd.leerIdNombreHorasCursosExistentesInscritos();
        ComboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(arrayString));
    }
private void comboBox4() {
        String arrayString[] = bd.leerIdNombreHorasCursosNoExistentesInscritos();
        ComboCurso1.setModel(new javax.swing.DefaultComboBoxModel<>(arrayString));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        Alineador = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaNew = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ComboNombre = new javax.swing.JComboBox<>();
        ComboNombre1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ComboCurso = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ComboCurso1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo.setBackground(new java.awt.Color(221, 214, 204));

        Alineador.setBackground(new java.awt.Color(221, 214, 204));

        TablaNew.setBackground(new java.awt.Color(25, 34, 43));
        TablaNew.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TablaNew.setForeground(new java.awt.Color(221, 214, 204));
        TablaNew.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "APELLIDO", "CORREO", "TELEFONO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaNew.setGridColor(new java.awt.Color(189, 146, 64));
        TablaNew.setSelectionBackground(new java.awt.Color(184, 67, 87));
        TablaNew.setSelectionForeground(new java.awt.Color(25, 34, 43));
        jScrollPane1.setViewportView(TablaNew);

        Alineador.add(jScrollPane1);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 34, 43));
        jLabel1.setText("SELECCIONE ALUMNO");

        ComboNombre.setBackground(new java.awt.Color(25, 34, 43));
        ComboNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ComboNombre.setForeground(new java.awt.Color(221, 214, 204));
        ComboNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNombreActionPerformed(evt);
            }
        });

        ComboNombre1.setBackground(new java.awt.Color(25, 34, 43));
        ComboNombre1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ComboNombre1.setForeground(new java.awt.Color(221, 214, 204));
        ComboNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNombre1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 34, 43));
        jLabel2.setText("SELECCIONE EXALUMNO");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 34, 43));
        jLabel3.setText("SELECCIONE VER INSCRIPCIONES DE UN ALUMNO O UN EXALUMNO");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 34, 43));
        jLabel4.setText("SELECCIONE CURSO");

        ComboCurso.setBackground(new java.awt.Color(25, 34, 43));
        ComboCurso.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ComboCurso.setForeground(new java.awt.Color(221, 214, 204));
        ComboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCursoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 34, 43));
        jLabel5.setText("SELECCIONE EXCURSO");

        ComboCurso1.setBackground(new java.awt.Color(25, 34, 43));
        ComboCurso1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ComboCurso1.setForeground(new java.awt.Color(221, 214, 204));
        ComboCurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCurso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(Alineador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(156, 156, 156))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(ComboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(ComboNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(ComboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(ComboCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Alineador, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNombreActionPerformed
        for (int i = 0; i <modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i--;
        }
        TablaNew.setModel(modelo);
        String parte[] = ComboNombre.getSelectedItem().toString().split(",");
        String datitos[]=bd.leerInscripcionesConAlumnoExistente(Integer.valueOf(parte[0]));
        for (int i = 0; i < bd.leerInscripcionesConAlumnoExistente(Integer.valueOf(parte[0])).length; i++) {
            modelo.addRow(datitos[i].split(","));
        }
        ComboNombre.setBackground(new Color(189, 146, 64));
        ComboNombre.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_ComboNombreActionPerformed

    private void ComboNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNombre1ActionPerformed
        for (int i = 0; i <modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i--;
        }
        TablaNew.setModel(modelo);
        String parte[] = ComboNombre1.getSelectedItem().toString().split(",");
        String datitos[]=bd.leerInscripcionesConAlumnoNoExistente(Integer.valueOf(parte[0]));
        for (int i = 0; i < bd.leerInscripcionesConAlumnoNoExistente(Integer.valueOf(parte[0])).length; i++) {
            modelo.addRow(datitos[i].split(","));
        }
        ComboNombre1.setBackground(new Color(189, 146, 64));
        ComboNombre1.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_ComboNombre1ActionPerformed

    private void ComboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCursoActionPerformed
        for (int i = 0; i <modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i--;
        }
        TablaNew.setModel(modelo);
        String parte[] = ComboCurso.getSelectedItem().toString().split(",");
        String datitos[]=bd.leerInscripcionesConCursoExistente(Integer.valueOf(parte[0]));
        for (int i = 0; i < bd.leerInscripcionesConCursoExistente(Integer.valueOf(parte[0])).length; i++) {
            modelo.addRow(datitos[i].split(","));
        }
        ComboCurso.setBackground(new Color(189, 146, 64));
        ComboCurso.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_ComboCursoActionPerformed

    private void ComboCurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCurso1ActionPerformed
        for (int i = 0; i <modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i--;
        }
        TablaNew.setModel(modelo);
        
        String parte[] = ComboCurso1.getSelectedItem().toString().split(",");
        String datitos[]=bd.leerInscripcionesConCursoNoExistente(Integer.valueOf(parte[0]));
        for (int i = 0; i < bd.leerInscripcionesConCursoNoExistente(Integer.valueOf(parte[0])).length; i++) {
            modelo.addRow(datitos[i].split(","));
        }
        ComboCurso1.setBackground(new Color(189, 146, 64));
        ComboCurso1.setForeground(new Color(25, 34, 43));
    }//GEN-LAST:event_ComboCurso1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscripcionesMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscripcionesMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscripcionesMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscripcionesMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscripcionesMostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alineador;
    private javax.swing.JComboBox<String> ComboCurso;
    private javax.swing.JComboBox<String> ComboCurso1;
    private javax.swing.JComboBox<String> ComboNombre;
    private javax.swing.JComboBox<String> ComboNombre1;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JTable TablaNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
